spring.application.name=mantencion

server.port=8089

# Configuración de Conexión a Neon DB (Ajusta con tus credenciales)
spring.datasource.url=jdbc:postgresql://ep-patient-frost-aq36cixk-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_5PFs2GmDXuey
spring.datasource.driver-class-name=org.postgresql.Driver

# Estrategia JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true